export const LIST_ALL="LIST_ALL";
export const CLOSE_FORM="CLOSE_FORM";
export const OPEN_FORM="OPEN_FORM";
export const UPDATE_STATUS_TASK="UPDATE_STATUS_TASK";
export const DELETE_TASK="DELETE_TASK";
export const SAVE_TASK="SAVE_TASK";
export const UPDATE_TASK_BUTTON="UPDATE_TASK_BUTTON";


